### ISSUE TITLE
Dragging and release the mouse causes game thinks the user is clicking

### ISSUE THREAD

**Issue by Kashouryo** [yugecin/opsu-dance#197]
opsu game version: Git pulled from master at Dec 12, 2018, 11:10 GMT+8

Expected behavior:
Drag and release a song in the song selection menu, the game will not start.

Actual behavior:
The game treats the release of drag as click and the song that is under the mouse cursor will start to play.

Video record: https://www.youtube.com/watch?v=ozbkV7zwmzI

Operating system: macOS 10.12 with JDK 1.8.0_144-b01

**Comment by yugecin** [comment]
thanks! fixed in latest release (0.5.0)
