### ISSUE TITLE
opsu wont start

### ISSUE THREAD

**Issue by SWlvl60** [yugecin/opsu-dance#278]
As soon as i want to start opsu (by double clicking the opsu-dance-0.5.1.jar file) it throws a cmd window with an "Could not find or load main class opsu-dance-0.5.1.jar" error. I dont know anything about code but i tried renaming the file into opsu!dance.jar, opsu_dance.jar and opsudance.jar, but nothing works. My system PATH variable is fine. How can i fix this?

**Comment by yugecin** [comment]
try this https://johann.loefflmann.net/en/software/jarfix/index.html

**Comment by SWlvl60** [comment]
> try this https://johann.loefflmann.net/en/software/jarfix/index.html

already tried that but it still shows the same error.

**Comment by yugecin** [comment]
in that case, just run it from cmd `java -jar opsu-dance-0.5.1.jar`

**Comment by SWlvl60** [comment]
> in that case, just run it from cmd `java -jar opsu-dance-0.5.1.jar`

still the same error. I have no idea whats wrong.

**Comment by yugecin** [comment]
that's very strange, as if it's ignoring the `-jar` option
try ` java -cp opsu-dance-0.5.1.jar yugecin.opsudance.core.Entrypoint`

**Comment by SWlvl60** [comment]
> that's very strange, as if it's ignoring the `-jar` option
> try ` java -cp opsu-dance-0.5.1.jar yugecin.opsudance.core.Entrypoint`

Yay, that worked, Thank you for your patience!

**Comment by yugecin** [comment]
glad it works :)
