### ISSUE TITLE
beatmaps not found when clicking play

### ISSUE THREAD

**Issue by myaccountgotdeleted** [yugecin/opsu-dance#303]
it says there is no beatmaps :( If there is a way to set either your osu! folder or import osk/osz files it doesn't work and i tried putting them in the SongPacks folder and it didnt work either

**Comment by myaccountgotdeleted** [comment]
![screenshot_20200301_122328](https://user-images.githubusercontent.com/60831434/75631328-7c410480-5bb7-11ea-87a0-6a3a3e5a0a43.png)
screenshot of opsu dance

![image](https://user-images.githubusercontent.com/60831434/75631348-ae526680-5bb7-11ea-9e1a-0d97d3a747bb.png)
screenshot of my opsu dance folder

**Comment by yugecin** [comment]
I think the SongPacks directory only accepts .osz files, try placing them in Songs or check the BeatmapDirectory value in the file .opsu.cfg

**Comment by myaccountgotdeleted** [comment]
Thanks I will try this

**Comment by myaccountgotdeleted** [comment]
Fixed it now and skins work :D
![image](https://user-images.githubusercontent.com/60831434/76913037-d8787980-6883-11ea-94e0-72e02af3882b.png)

**Comment by myaccountgotdeleted** [comment]
opsu keeps resetting my beatmaps folder to opsu!dance\Songs even though it doesnt exist and still gets songs so before opening it I change it to my osu! directory (D:\osu2015\Songs)
Anyway since I got it fixed I'll close it here.
