### ISSUE TITLE
Game not updating

### ISSUE THREAD

**Issue by Redstonneur1256** [yugecin/opsu-dance#305]
When I launch the game, I need to do the update before using it, I wait for the download end, and when the download is complete the game restart and need another update.

**Comment by myaccountgotdeleted** [comment]
When it restarts click update and then it will say update failed then you can play. It happens to me but it actually made a new jar file so i can use the new one so i dont have to update anymore

**Comment by yugecin** [comment]
fixed (you might need to update one last time)

**Comment by yugecin** [comment]
also you never _have_ to update before using it
