### ISSUE TITLE
Sliders wont render after crash

### ISSUE THREAD

**Issue by Chaaoos** [yugecin/opsu-dance#35]
opsu crashed at the end of a certain spinner on a certain map, --> https://aww.moe/0omee7.mp4
when i restarted sliders wont render --> https://aww.moe/hjtpom.mp4

**Comment by Chaaoos** [comment]
forgot to say spinner was rekt and spinner delay was 0ms

**Comment by yugecin** [comment]
Sliders not rendering probably not caused by the crash that happend (see #24 sliders dont render)
Not sure why it crashed at the spinner, but I just tested it now and seems fine, reopen if that is not the case
