### ISSUE TITLE
Some note in the map IAHN - Transform [Aspire] dont render and the cursor just sits and spins

### ISSUE THREAD

**Issue by Name-The-Best** [yugecin/opsu-dance#39]
[here's](https://my.mixtape.moe/tppsty.gif) a gif of it

**Comment by yugecin** [comment]
> McKay: also, the bug here for the slidertime being too long: http://trigger.s-ul.eu/9zWIkcto.mp4
that's because peppy clamps the msPerBeat to between 10 and 1000 (and not clamping it results in too long sliders on such maps) in the timingpoints(edited)

**Comment by yugecin** [comment]
stuff not rendering is caused by the breaks

**Comment by yugecin** [comment]
fixed in c0acb7a

**Comment by yugecin** [comment]
also fixed in upstream: itdelatrisu/opsu#209
