### ISSUE TITLE
Cursor Color Bug !

### ISSUE THREAD

**Issue by WolfSiZe** [yugecin/opsu-dance#45]
Hello , I play opsu dance and When I want to set Combo1's color in color override and Cursor color override , ingame , the colors aren't sames , if u can help me !

**Comment by yugecin** [comment]
Weird, they are the same when I do it

**Comment by yugecin** [comment]
https://i.gyazo.com/thumb/1200/_c7d6198564a9efda7f741099bdf06715-png.jpg
(perhaps mouse cursor is not white)
