### ISSUE TITLE
option to show epilepsy warning in the beginning?

### ISSUE THREAD

**Issue by yugecin** [yugecin/opsu-dance#48]

**Comment by Chaaoos** [comment]
![epilepsy 2x](https://cloud.githubusercontent.com/assets/22846042/20247628/f75df156-a9d0-11e6-8b52-c06d0a48ab7f.png)

Then can we use the original one?

**Comment by yugecin** [comment]
I'd like to, but can we? copyright & stuff idk

**Comment by yugecin** [comment]
Feel like making a clone of it @Chaaoos? maybe witht he same colors as the logo or sth :p

**Comment by Mrkevin809** [comment]
I have nice image for this.

**Comment by yugecin** [comment]
added in a1a9dde
if everyone can make a better img, feel free :)
