### ISSUE TITLE
opsu-dance crashes with the beatmap : "IAHN - Transform"

### ISSUE THREAD

**Issue by dinnozap** [yugecin/opsu-dance#5]
I downloaded the beatmap "IAHN - Transform" from the in-game downloader and I got this error ![Error](http://puu.sh/rug0A/0682e8715a.jpg)
Now, everytime I launch the client, this error message is poping.

**Comment by Goldkraw** [comment]
This also happens when you select "IAHN - Transform [Aspire]" in the song select screen

**Comment by yugecin** [comment]
That specific map is known to cause problems. Is it the only map you have right now? If it is, just delete it from the songs folder untill it's resolved. If it isn't: that would be weird.
I'm going to have a fix soon that will prevent it from crashing (but weird things will still happen when playing the map)

**Comment by yugecin** [comment]
New release containing fix:
https://github.com/yugecin/opsu-dance/releases/tag/0.1.1
It stops it from crashing, but due to the aspire behaviour, it doesn't play the same way like in osu!
