### ISSUE TITLE
opsu-dance randomly freezes and crashes

### ISSUE THREAD

**Issue by AwesomeGamer89** [yugecin/opsu-dance#54]
During the middle of a song the game crashes for no apparent reason!!!PLEASE FIX!!!

**Comment by Awlexus** [comment]
if you can reproduce it, you might as well copy the error in your issue

**Comment by yugecin** [comment]
^ or give a link to the map if it's always in the same map

**Comment by jamesguessis** [comment]
I have the same exact issue with the same exact error output!!!PLEASE FIX!!!

**Comment by AwesomeGamer89** [comment]
no there is no code or map problem! just randomly

**Comment by yugecin** [comment]
which white screen are you referring to?

**Comment by AwesomeGamer89** [comment]
the: Opsu is not responding then there are 2options that say 

                   ____________________________________________________________________ 
                   |                                   (Windows Dialog)                                     |
                   l                                                                                                    |
                    |                                                                                                   |
                   l                                Opsu is not responding                               |
                   l                                                                                                     |
                   l                                      __________________                                    |
                   l                                      | Close Window |                                    |
                   l                                      -------------------                                   |
                   l                                                                                                     |
                   l                                        ______________________                           |
                   l                                        | Wait till it responds|                           |
                   l                                        -----------------------                           |
                   ----------------------------------------------------------------------


                                 BTW thsi took me forever

**Comment by Awlexus** [comment]
That's actually strange. Is it also happening, when you play normally (without auto) or only while dancing?

**Comment by AwesomeGamer89** [comment]
dancing
