### ISSUE TITLE
possible timing section issue  

### ISSUE THREAD

**Issue by Name-The-Best** [yugecin/opsu-dance#6]
when ever there's a timing section change (i think) the gui flashes

**Comment by yugecin** [comment]
Do you have an example? map/timestamp?

**Comment by Name-The-Best** [comment]
what do you mean. like i could make a gif

**Comment by yugecin** [comment]
is there a beamap that has such a timing section change so I can see it myself and test it?

**Comment by Name-The-Best** [comment]
ok. so the beat maps i tested in were https://osu.ppy.sh/s/12483 and https://osu.ppy.sh/s/191723 . this is the gif https://my.mixtape.moe/hyctri.gif

**Comment by yugecin** [comment]
I see, it's on every map. Seems like it happens when a new circle is drawn when there's no other circle currently drawn.
