### ISSUE TITLE
Can't reach the back button!!!!

### ISSUE THREAD

**Issue by AwesomeGamer89** [yugecin/opsu-dance#61]
i can't go lower to reach the back button before the mouse turns into the regular desktop mouse and if i click while its in the desktop mouse it brings me back to the home screen of my computer but Opsu is still playing in the back round basicly what im saying is that i cant go lower than the time in the bottom left corner any where so all the way from left to right i can go there with my cursor

**Comment by yugecin** [comment]
Try making sentences.
Maybe the back button in your skin is very small.
Also did you try pressing the escape key?

**Comment by AwesomeGamer89** [comment]
close the issue
also will you be on osu today?
it was a bug with my computer
