### ISSUE TITLE
Add delay movement cursor while dance

### ISSUE THREAD

**Issue by ModiFlasher** [yugecin/opsu-dance#80]
Sometimes cursor dance move so fast and this make FPS drop down for low spec PC

**Comment by yugecin** [comment]
Cursor dance too fast? Do you mean the maps you are playing are so fast it causes lag?
What is your suggestion? I don't quite understand what 'delay movement cursor while dance' should do or what difference it should make.

**Comment by jamesguessis** [comment]
I would like you to add a 30ms lag from cursor movement while trying to use opsu-dance as an alternative to osu.

**Comment by yugecin** [comment]
I don't get it, can you explain?
